# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cb34a8d081143220647c5fc08513b17144448e69e08bb740c3f645cb7d8f123eab68f386795488f418fffc0749824f411d7913a722402fcbaaef49a13c941ee

test:
  secret_key_base: ca2912394cacc9bf11d53b8dc8a6760d777cf8488f012041943e5baced6e2cb9d06e48ff5ebb53ec6f2b9e5b3951d1e7ce7e65eb237e2c6fdeff007a8ab36f4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
